### ISSUE TITLE
Create PR to LLVM for generating CMTI files

### ISSUE THREAD

**Issue by taquangtrung** [sbip-sg/discover-analyzer#3]
**Problem**

The current Ocaml bindings shipped with LLVM don't contain `*.cmti` files, which are needed for productive OCaml coding: code navigation, outline, etc.

**Solution**

Create a PR to LLVM project to generate such `*.cmti` files.

**Comment by tnkhanh** [comment]
Submitted patch. Waiting for review https://reviews.llvm.org/D110983

**Comment by taquangtrung** [comment]
Great! Could you create a PR to: https://github.com/sbip-sg/llvm-project too?

**Comment by tnkhanh** [comment]
Yes. I created a PR
