### ISSUE TITLE
Check if Gollvm bindings compatible with LLVM 13

### ISSUE THREAD

**Issue by taquangtrung** [sbip-sg/discover-analyzer#9]
Check with LLVM 13 rc3 first, since the official release of LLVM 13 isn't available yet.

**Comment by tnkhanh** [comment]
gollvm cannot build with llvm13 rc3 or rc1. I am asking gollvm team for support.

**Comment by tnkhanh** [comment]
gollvm (latest version) can now build with LLVM13 rc3 and rc1.
To build Ocaml bindings, do:
```
cmake [..] -DLLVM_ENABLE_BINDINGS=ON
ninja ocaml_doc
ninja install
```
